import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Script from 'next/script'
import styles from '../styles/Home.module.css'

import Header from '../components/Header'
import Main from '../components/Main'
import Footer from '../components/Footer'
import MintPage from './homepage'

import tw from "tailwind-styled-components"
import RoadMap from '../components/RoadMap'

const Container = tw.div`
  w-screen
  h-screen
  bg-black
  text-white
  px-5
`


export default function Home() {
  return (
    <Container >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        id="tailwind"
        src="https://cdn.tailwindcss.com"
      />
      <Header />
      <Main />

    </Container>
  )
}
